theme: practical-club-website-template
title: Beyond the Cube
description: "Beyond the Cube: Mastering Problem-Solving Through Rubik's Wisdom"
url: "https://beyondthecube.github.io"

minima:
  skin: auto
  nav_pages:
    - index.md
    - phcubers.md
    - ph-ormula.md

plugins:
  - jekyll-seo-tag
  - jekyll-feed

kramdown:
  math_engine: mathjax
  input: GFM

exclude:
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - Gemfile.lock
  - GEMINI.md